deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Print environment variables for debugging
      run: |
        echo "FTP_SERVER: $FTP_SERVER"
        echo "FTP_USERNAME : $FTP_USERNAME"
      env:
        FTP_SERVER: ftp.bengkaliskab.org
        FTP_USERNAME: sipela@reservasilab.bengkaliskab.org

    - name: Test FTP Connection
      run: nc -zv $FTP_SERVER 21

    - name: Deploy to server via FTP
      run: |
        # Periksa apakah ada commit sebelumnya, dan buat diff hanya jika ada commit sebelumnya
        COMMIT_RANGE=${GITHUB_SHA}^..${GITHUB_SHA}
        if ! git rev-parse --verify $COMMIT_RANGE >/dev/null 2>&1; then
          # Jika tidak ada commit sebelumnya, gunakan HEAD~1..HEAD untuk mendapatkan perubahan
          COMMIT_RANGE=HEAD~1..HEAD
        fi
        git diff --name-only $COMMIT_RANGE > changed_files.txt
        # Filter file yang diubah dan kirim ke FTP
        cat changed_files.txt | xargs -I {} lftp -f "
        set ftp:ssl-allow no
        open $FTP_SERVER
        user $FTP_USERNAME $FTP_PASSWORD
        mirror --reverse --only-newer --delete --verbose ./{} /path/on/ftp/server/{}
        bye
        "
      env:
        FTP_SERVER: ftp.bengkaliskab.org
        FTP_USERNAME: sipela@reservasilab.bengkaliskab.org
        FTP_PASSWORD: Sipela123
