name: CI/CD Pipeline

on:
  push:
    branches: ["master"] # Menjalankan pipeline pada push ke branch master
  pull_request:
    branches: ["master"] # Menjalankan pipeline saat ada pull request ke branch master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Mengambil kode dari repositori

      - name: Install lftp
        run: sudo apt-get install -y lftp # Menginstal lftp untuk proses deployment FTP

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Configure environment file
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run Laravel migrations
        run: php artisan migrate --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run Laravel tests
        run: php artisan test --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Print environment variables for debugging
        run: |
          echo "FTP_SERVER: $FTP_SERVER"
          echo "FTP_USERNAME : $FTP_USERNAME"
        env:
          FTP_SERVER: ftp.bengkaliskab.org
          FTP_USERNAME: sipela@reservasilab.bengkaliskab.org

      - name: Test FTP Connection
        run: nc -zv ftp.bengkaliskab.org 21

      - name: Deploy to server via FTP
        run: |
          # Checkout history penuh
          git fetch --prune --unshallow

          # Periksa apakah ada commit sebelumnya
          if git rev-parse --verify HEAD^ &>/dev/null; then
            echo "Commit sebelumnya ditemukan, melanjutkan dengan git diff."
            git diff --name-only HEAD^..HEAD > changed_files.txt
          else
            echo "Tidak ada commit sebelumnya, menggunakan commit saat ini."
            git diff --name-only HEAD > changed_files.txt
          fi

          # Periksa apakah ada file yang diubah
          if [ -s changed_files.txt ]; then
            echo "File yang diubah ditemukan. Mengirim ke FTP."

            # Kirim file yang diubah ke FTP
            while IFS= read -r file; do
              # Abaikan jika "file" adalah direktori
              if [ -d "$file" ]; then
                echo "Lewati direktori: $file"
                continue
              fi

              # Periksa apakah file ada
              if [ -f "$file" ]; then
                remote_path="/path/on/ftp/server/$file"
                remote_dir=$(dirname "$remote_path")

                echo "Mengunggah file: $file ke $remote_path"

                # Upload file menggunakan lftp
                lftp -e "
                  set ftp:ssl-allow no
                  open $FTP_SERVER
                  user $FTP_USERNAME $FTP_PASSWORD
                  # Hapus file lama jika ada
                  rm -f \"$remote_path\" || true
                  # Pastikan direktori tujuan ada
                  mkdir -p \"$remote_dir\" || true
                  # Unggah file
                  put \"$file\" -o \"$remote_path\"
                  bye
                "
              else
                echo "File tidak ditemukan: $file"
              fi
            done < changed_files.txt
          else
            echo "Tidak ada perubahan file, tidak ada yang dikirim ke FTP."
          fi
            bye
          "
        env:
          FTP_SERVER: ftp.bengkaliskab.org
          FTP_USERNAME: sipela@reservasilab.bengkaliskab.org
          FTP_PASSWORD: Sipela123
