name: CI/CD Pipeline

on:
  push:
    branches: ["master"] # Menjalankan pipeline pada push ke branch master
  pull_request:
    branches: ["master"] # Menjalankan pipeline saat ada pull request ke branch master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Mengambil kode dari repositori

      - name: Install lftp
        run: sudo apt-get install -y lftp # Menginstal lftp untuk proses deployment FTP

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Configure environment file
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run Laravel migrations
        run: php artisan migrate --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run Laravel tests
        run: php artisan test --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Print environment variables for debugging
        run: |
          echo "FTP_SERVER: $FTP_SERVER"
          echo "FTP_USERNAME : $FTP_USERNAME"
        env:
          FTP_SERVER: ftp.bengkaliskab.org
          FTP_USERNAME: sipela@reservasilab.bengkaliskab.org

      - name: Test FTP Connection
        run: nc -zv ftp.bengkaliskab.org 21

      - name: Deploy to server via FTP
        run: |
          # Periksa apakah ada commit sebelumnya, dan buat diff hanya jika ada commit sebelumnya
          COMMIT_RANGE=${GITHUB_SHA}^..${GITHUB_SHA}
          if ! git rev-parse --verify $COMMIT_RANGE >/dev/null 2>&1; then
            # Jika tidak ada commit sebelumnya, gunakan HEAD~1..HEAD untuk mendapatkan perubahan
            COMMIT_RANGE=HEAD~1..HEAD
          fi
          # Hanya file yang diubah yang akan di-upload
          git diff --name-only $COMMIT_RANGE > changed_files.txt
          # Filter file yang diubah dan kirim ke FTP
          cat changed_files.txt | xargs -I {} lftp -f "
          set ftp:ssl-allow no
          open $FTP_SERVER
          user $FTP_USERNAME $FTP_PASSWORD
          mirror --reverse --only-newer --delete --verbose ./{} /path/on/ftp/server/{}
          bye
          "
        env:
          FTP_SERVER: ftp.bengkaliskab.org
          FTP_USERNAME: sipela@reservasilab.bengkaliskab.org
          FTP_PASSWORD: Sipela123
